name = "Sophus"
uuid = "5fdcd198-557d-5aab-91f7-0b03ebc48aac"
authors = ["Amin Abouee <Amin.Abouee@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
